export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_MOVIES_SUCCESS = "GET_POPULAR_MOVIES_SUCCESS";
export const GET_POPULAR_MOVIES_FAIL = "GET_POPULAR_MOVIES_FAIL";


export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAIL = "SEARCH_MOVIES_FAIL";